export const campaignConstants = {
  CREATE_REQUEST: "CAMPAIGN_CREATE_REQUEST",
  CREATE_SUCCESS: "CAMPAIGN_CREATE_SUCCESS",
  CREATE_FAILURE: "CAMPAIGN_CREATE_FAILURE",

  UPDATE_REQUEST: "CAMPAIGN_UPDATE_REQUEST",
  UPDATE_SUCCESS: "CAMPAIGN_UPDATE_SUCCESS",
  UPDATE_FAILURE: "CAMPAIGN_UPDATE_FAILURE",

  DELETE_REQUEST: "CAMPAIGN_DELETE_REQUEST",
  DELETE_SUCCESS: "CAMPAIGN_DELETE_SUCCESS",
  DELETE_FAILURE: "CAMPAIGN_DELETE_FAILURE",
};
