export const characterConstants = {
  CREATE_REQUEST: 'CHARACTER_CREATE_REQUEST',
  CREATE_SUCCESS: 'CHARACTER_CREATE_SUCCESS',
  CREATE_FAILURE: 'CHARACTER_CREATE_FAILURE',

  UPDATE_REQUEST: 'CHARACTER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CHARACTER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CHARACTER_UPDATE_FAILURE',

  DELETE_REQUEST: 'CHARACTER_DELETE_REQUEST',
  DELETE_SUCCESS: 'CHARACTER_DELETE_SUCCESS',
  DELETE_FAILURE: 'CHARACTER_DELETE_FAILURE',
};