export const partyConstants = {
  CREATE_REQUEST: "PARTY_CREATE_REQUEST",
  CREATE_SUCCESS: "PARTY_CREATE_SUCCESS",
  CREATE_FAILURE: "PARTY_CREATE_FAILURE",

  UPDATE_REQUEST: "PARTY_UPDATE_REQUEST",
  UPDATE_SUCCESS: "PARTY_UPDATE_SUCCESS",
  UPDATE_FAILURE: "PARTY_UPDATE_FAILURE",

  DELETE_REQUEST: "PARTY_DELETE_REQUEST",
  DELETE_SUCCESS: "PARTY_DELETE_SUCCESS",
  DELETE_FAILURE: "PARTY_DELETE_FAILURE",
};
